/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2e3a8872-dbaa-4dfc-b44c-7ea066187ef5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CoiZss2r3",
    "aws_user_pools_web_client_id": "ji4rgrmabbag8pa76k1al2fi",
    "oauth": {},
    "aws_user_files_s3_bucket": "encs691k-item-images155906-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
